export const wikiImageMap: Record<string, string> = {
  "Chicken Tinola": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Tinola.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Fruit Salad Filipino Style": "https://placehold.co/600x400/0fa958/ffffff.png?text=Fruit%20Salad%20Filipino%20Style",
  "Tortang Itlog": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Open_toast_-_spanish_omelette.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sinangag": "https://upload.wikimedia.org/wikipedia/commons/5/50/Lutong_Bahay_-_Chorizo_with_hard_boiled_egg%2C_tomatoes%2C_grapes_and_garlic_fried_rice.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Guisadong Gulay": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Mechado": "https://upload.wikimedia.org/wikipedia/commons/4/48/Pinoy_Pandesal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sinigang na Baboy": "https://placehold.co/600x400/0fa958/ffffff.png?text=Sinigang%20na%20Baboy",
  "Adobong Manok": "https://upload.wikimedia.org/wikipedia/commons/5/5a/ADOBONG_MANOK_SA_SARSA.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sotanghon Guisado": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Tinuktok_in_Camarines_Sur.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Nilagang Baboy": "https://placehold.co/600x400/0fa958/ffffff.png?text=Nilagang%20Baboy",
  "Inihaw na Pusit": "https://placehold.co/600x400/0fa958/ffffff.png?text=Inihaw%20na%20Pusit",
  "Ginataang Puso ng Saging": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Foods_cuisine_of_the_Philippines_Bulacan_05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Embutido": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Feijoada_%28Brazilian_dish%29%2C_S%C3%A3o_Lu%C3%ADs%2C_Maranh%C3%A3o.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Adobo": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Chicken_Adobo_with_Coconut_Milk.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Adobo": "https://upload.wikimedia.org/wikipedia/commons/2/23/Adobo_Filipino_sa_%27gata%27.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Sinigang": "https://upload.wikimedia.org/wikipedia/commons/d/db/Puto_Sikwate.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Shrimp Sinigang": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Bulalo": "https://upload.wikimedia.org/wikipedia/commons/6/66/Bulalo_%28Philippines%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Kare-Kare": "https://upload.wikimedia.org/wikipedia/commons/0/03/Inbound2958243268449135041.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pinakbet": "https://upload.wikimedia.org/wikipedia/commons/6/69/Pinakbet3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bicol Express": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Bicol_Express.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Eggplant Omelet": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Saut\u00e9ed Bitter Gourd": "https://upload.wikimedia.org/wikipedia/commons/1/16/Adobong_Tuyo_at_La_Herencia_Comida.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Steak": "https://upload.wikimedia.org/wikipedia/commons/1/17/Beef_steak_with_side_dish_in_dinner.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Fried Spring Rolls": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Indian_Spring_Rolls_with_spicy_red_chilli_%28Dalle_Khursani%29_chutney_DSC_0741.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Afritada": "https://upload.wikimedia.org/wikipedia/commons/3/32/Tinuktok.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Menudo": "https://upload.wikimedia.org/wikipedia/commons/6/69/DSCF1009_Hearty_fish_stew_simmering_in_a_rich_orange_broth_studded_with_tender_chunks_of_fish_and_vegetables.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Squash in Coconut Milk": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Foods_cuisine_of_the_Philippines_Bulacan_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Boiled Beef Soup": "https://upload.wikimedia.org/wikipedia/commons/b/bf/KOCIS_Mul-naengmyeon%2C_Chilled_Buckwheat_Noodle_Soup_%284594756202%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sizzling Pork Sisig": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Sisig_with_mayonnaise.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Fried Milkfish": "https://upload.wikimedia.org/wikipedia/commons/8/86/CHANOS_CHANOS_BANGUS_MILKFISH_FROM_PANGASINAN.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bangus Paksiw": "https://upload.wikimedia.org/wikipedia/commons/b/b5/503Paksiw_na_Isda_41.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Adobo String Beans": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Tamale_pie_close-up_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Lechon Kawali": "https://upload.wikimedia.org/wikipedia/commons/8/88/Lechon_Kawali_meal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pancit Canton": "https://upload.wikimedia.org/wikipedia/commons/2/2b/A_Savory_Squash_Pancit.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pancit Bihon": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Pancit_canton.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Arroz Caldo": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Arroz_caldoso%2C_Espa%C3%B1a.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Caldereta": "https://upload.wikimedia.org/wikipedia/commons/7/71/Morcon_and_caldereta.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Igado": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Food_to_Go_with_Igado.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Dinuguan": "https://upload.wikimedia.org/wikipedia/commons/8/89/Rustic_outdoor_cooking_of_meat_in_preparation_for_Dinuguan_dish_%28cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Monggo Guisado": "https://upload.wikimedia.org/wikipedia/commons/1/19/Sweet_potato_and_lubi-lubi_duchess.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginataang Tilapia": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Fish_with_coconut_milk.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bangus Sisig": "https://upload.wikimedia.org/wikipedia/commons/4/48/Pinoy_Pandesal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Tokwa and Pork": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Tokwa_at_Baboy.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Saut\u00e9ed Bottle Gourd": "https://upload.wikimedia.org/wikipedia/commons/1/16/Adobong_Tuyo_at_La_Herencia_Comida.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Filipino Sweet and Sour Pork": "https://upload.wikimedia.org/wikipedia/commons/9/98/ParesKanto.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Filipino Chicken Curry": "https://upload.wikimedia.org/wikipedia/commons/1/10/A_chicken_curry_dish.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Jackfruit in Coconut Milk": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Ginataang_Langka.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Laing": "https://upload.wikimedia.org/wikipedia/commons/5/59/Laing%2C_Bicolano_dish.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Escabeche": "https://upload.wikimedia.org/wikipedia/commons/4/41/Bonito_escabeche_%28tapa%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Filipino Pork BBQ": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Pork_BBQ.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Fresh Spring Rolls": "https://upload.wikimedia.org/wikipedia/commons/e/e5/DFC_5092_Crispy_golden_spring_rolls_served_hot_with_a_tangy_dipping_sauce_and_fresh_lettuce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chopsuey": "https://upload.wikimedia.org/wikipedia/commons/9/9d/American_Chopsey.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Inasal": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Calenderia_by_Felix_Laureano_Recuerdos_de_Filipinas.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Tocino": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Pinoy_-_Filipino_street_food.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Pares": "https://upload.wikimedia.org/wikipedia/commons/f/fa/BeefParesMamiStall.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Lumpiang Gulay": "https://upload.wikimedia.org/wikipedia/commons/1/19/Sweet_potato_and_lubi-lubi_duchess.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginataang Alimango": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Tuyo_at_Champorado.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Tapa": "https://upload.wikimedia.org/wikipedia/commons/8/88/Philippine_Food.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Banana Cue": "https://upload.wikimedia.org/wikipedia/commons/5/56/0768Partially_nude_boys_of_the_Philippines_skateboarding_15.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Humba": "https://upload.wikimedia.org/wikipedia/commons/4/41/Humba_%28Philippines%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Pochero": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginisang Pechay": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Kinilaw na Tuna": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Binagoongan": "https://upload.wikimedia.org/wikipedia/commons/3/32/Tinuktok.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Tortang Giniling": "https://upload.wikimedia.org/wikipedia/commons/3/32/Tinuktok.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Macaroni Salad": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Foods_cuisine_of_the_Philippines_Bulacan_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Empanada": "https://upload.wikimedia.org/wikipedia/commons/9/98/Tonkatsu_003.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pesang Manok": "https://upload.wikimedia.org/wikipedia/commons/4/48/Pinoy_Pandesal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Adobong Pusit": "https://upload.wikimedia.org/wikipedia/commons/6/65/Adobong_pusit.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Kansi": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Cansi.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Papaitan": "https://upload.wikimedia.org/wikipedia/commons/2/29/Papaitan_%28Philippines%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Inihaw na Bangus": "https://upload.wikimedia.org/wikipedia/commons/3/32/Tinuktok.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Lumpiang Ubod": "https://upload.wikimedia.org/wikipedia/commons/d/db/Puto_Sikwate.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginataang Manok": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bopis": "https://upload.wikimedia.org/wikipedia/commons/f/fc/0001jfPhilippine_cuisine_dishes_Baliuag_Bulacafvf_31.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pancit Palabok": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Pancit_Palabok_%281%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Mami": "https://upload.wikimedia.org/wikipedia/commons/4/48/Pinoy_Pandesal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Lomi": "https://upload.wikimedia.org/wikipedia/commons/f/f7/BATANGAS_LOMI.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginisang Sayote": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Afritada": "https://upload.wikimedia.org/wikipedia/commons/d/db/Puto_Sikwate.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Sisig": "https://upload.wikimedia.org/wikipedia/commons/3/36/Mac_MG_6046.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sinampalukang Manok": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Utan_Bisaya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sarciadong Isda": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginataang Hipon": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Asado": "https://upload.wikimedia.org/wikipedia/commons/0/07/Cochinillo_asado-Madrid.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bulanglang": "https://upload.wikimedia.org/wikipedia/commons/4/4a/BULANGLANG_NA_KAMANSI_WITH_LONG_GREEN_CHILI.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Taho": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Foods_cuisine_of_the_Philippines_Bulacan_05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Tinolang Isda": "https://upload.wikimedia.org/wikipedia/commons/d/db/Puto_Sikwate.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bistek Baboy": "https://upload.wikimedia.org/wikipedia/commons/4/48/Pinoy_Pandesal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Camaron Rebosado": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Camaron_Rebosado.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Beef Salpicao": "https://upload.wikimedia.org/wikipedia/commons/d/db/Puto_Sikwate.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bagoong Rice": "https://upload.wikimedia.org/wikipedia/commons/8/81/Milkfish._%28Bangus%29_%2818418215776%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Paksiw na Pata": "https://upload.wikimedia.org/wikipedia/commons/1/19/Sweet_potato_and_lubi-lubi_duchess.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Empanada": "https://upload.wikimedia.org/wikipedia/commons/3/32/Tinuktok.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginisang Patola": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tilapia_steak_and_mashed_bungkukan_with_lemon_cream_sauce.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "KBL": "https://upload.wikimedia.org/wikipedia/commons/9/92/Foods_cuisine_of_the_Philippines_Bulacan_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Bibingka": "https://upload.wikimedia.org/wikipedia/commons/9/98/ParesKanto.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Miki Bihon": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pinaypay_na_Saging.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pininyahang Manok": "https://upload.wikimedia.org/wikipedia/commons/8/8a/3715Common_houseflies_eating_Pininyahang_Manok_18.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Rellenong Bangus": "https://upload.wikimedia.org/wikipedia/commons/8/81/Milkfish._%28Bangus%29_%2818418215776%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Inihaw na Liempo": "https://upload.wikimedia.org/wikipedia/commons/3/32/Tinuktok.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Adobong Kangkong": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Stir-fried_Water_Convolvulus_%28%E7%82%92%E7%A9%BA%E5%BF%83%E8%8F%9C%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sinigang na Isda": "https://upload.wikimedia.org/wikipedia/commons/3/32/Tinuktok.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Suam na Mais": "https://upload.wikimedia.org/wikipedia/commons/4/48/Pinoy_Pandesal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Ginisang Togue": "https://upload.wikimedia.org/wikipedia/commons/1/19/Sweet_potato_and_lubi-lubi_duchess.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sweet and Sour Fish": "https://upload.wikimedia.org/wikipedia/commons/0/02/-2019-07-10_King_Prawn%2C_courgette_farfalle_in_sweet_and_sour_sauce%2C_Cromer.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Arroz Valenciana": "https://upload.wikimedia.org/wikipedia/commons/a/a8/ArrozalaValenciana.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pork Picadillo": "https://upload.wikimedia.org/wikipedia/commons/1/19/Sweet_potato_and_lubi-lubi_duchess.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Asado": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Calenderia_by_Felix_Laureano_Recuerdos_de_Filipinas.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Kwek-Kwek": "https://upload.wikimedia.org/wikipedia/commons/8/88/Philippine_Food.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Halo-Halo": "https://upload.wikimedia.org/wikipedia/commons/8/88/Philippine_Food.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Carioca": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Palitaw_Filipino_Delicacy.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Maja Blanca": "https://upload.wikimedia.org/wikipedia/commons/6/63/Bloki_na_ulicy_Goszczynskiego_Sosnowiec_%C5%9Arodula_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Dinakdakan": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Dinakdakan.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Turon": "https://upload.wikimedia.org/wikipedia/commons/2/22/Fried_Banana_Balls.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Sapin-Sapin": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Arboretum_et_fruticetum_Britannicum_-_Abies_alba_%2819130231843%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Puto": "https://upload.wikimedia.org/wikipedia/commons/8/84/0880Del_Monte_Sardine_Chicken_rice_%28Filipino_dish%29_04.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Pancit Luglug": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Pancit_Palabok_%28BGC_Taguig_City%29_06.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  "Chicken Pastel": "https://upload.wikimedia.org/wikipedia/commons/8/87/Filipino_Chicken_Pastel.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original"
};